--- 
title: "Produtos Fitossanintários"
author: "Endrio Webers"
format: 
  dashboard:
    logo: images/penguins.png
    nav-buttons: [linkedin, github]
    theme: yeti
editor_options: 
  chunk_output_type: inline
--- 

```{r}
#| context: setup
library(tidyverse)
library(bslib)
library(bsicons)
library(shiny)
library(DT)
library(readxl)
# importando e filtrando o banco de dados
dataset <- read_excel("data/produtos_fitossanitarios_nov_24.xlsx") |> 
  select(MARCA_COMERCIAL,
         FORMULACAO,
         INGREDIENTE_ATIVO,
         TITULAR_DE_REGISTRO,
         CLASSE,
         MODO_DE_ACAO,
         CULTURA,
         PRAGA_NOME_CIENTIFICO,
         PRAGA_NOME_COMUM,
         CLASSE_TOXICOLOGICA,
         CLASSE_AMBIENTAL,
         ORGANICOS)

```
```{r}
classes = dataset |> 
  select(CLASSE) |> 
  pull(CLASSE) |> 
  unique()


```



# {.sidebar}

```{r}

#| title: "Tipping Behavior"

selectizeInput(
  inputId = "classe_selecionada",
  label = "Selecione uma ou mais classes:",
  choices = classes,
  #selected = NULL,
  multiple = TRUE,
  options = list(placeholder = "Escolha as classes...")
)
```

```{r}
#| title: "Tipping Behavior"

```


# Plots

## Row {height="65%"}

```{r}
#| fig-width: 10
#| fig-height: 8
plot(cars)
```

## Row {height="35%"}
        
```{r}
#| fig-width: 5
#| fig-height: 4
plot(pressure)
```
    
```{r}
#| title: "Tipping Behavior"
#| layout-ncol: 2
#| fig-width: 5
#| fig-height: 4
plot(airmiles)
plot(pressure)
```


```{r}

value_box(
  title = "Value",
  value = textOutput("valuetext"),
  showcase = bs_icon("music-note-beamed")
)

```

# Dados

```{r}
datatable(dataset)
```

